apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-redis
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: redis
  template:
    metadata:
      labels:
        app: vote
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis

---
apiVersion: v1
kind: Service
metadata:
  name: vote-redis
  labels:
    app: vote
spec:
  selector:
    app: vote
    tier: redis
  ports:
  - port: 6379


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-postgres
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: postgres
  template:
    metadata:
      labels:
        app: vote
        tier: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        ports:
        - containerPort: 5432
          name: postgres
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: vote-postgres
  labels:
    app: vote
spec:
  selector:
    app: vote
    tier: postgres
  ports:
  - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: vote
      tier: worker
  template:
    metadata:
      labels:
        app: vote
        tier: worker
    spec:
      containers:
      - name: worker
        image: ghcr.io/subicura/voting/worker:latest
        env:
          - name: REDIS_HOST
            value: vote-redis
          - name: REDIS_PORT
            value: "6379"
          - name : POSTGRES_HOST
            value: vote-postgres
          - name: POSTGRES_PORT
            value: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-vote
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: vote
  template:
    metadata:
      labels:
        app: vote
        tier: vote
    spec:
      containers:
      - name: vote
        image: ghcr.io/subicura/voting/vote:latest
        ports:
        - containerPort: 80
          name: vote
        env:
          - name: REDIS_HOST
            value: vote-redis
          - name: REDIS_PORT
            value: '6379'
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        

---
apiVersion: v1
kind: Service
metadata:
  name: vote-vote
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    app: vote
    tier: vote
  ports:
  - port: 80
    nodePort: 31000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-result
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
      tier: result
  template:
    metadata:
      labels:
        app: vote
        tier: result
    spec:
      containers:
      - name: result
        image: ghcr.io/subicura/voting/result:latest
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_HOST
            value: vote-postgres
          - name: POSTGRES_PORT
            value: "5432"
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vote-result
  labels:
    app: vote
spec:
  type: NodePort
  selector:
    app: vote
    tier: result
  ports:
  - port: 80
    nodePort: 31001




